### ISSUE TITLE
Update facet search response

### ISSUE THREAD

**Issue by nickevansuk** [imin-ltd/prototype#10]
1. Update the endpoint https://search-beta.imin.co/v2/sessions in accordance with [this issue](https://github.com/openactive/opportunity-api/issues/5) and the below by adding `ext:facet`
2. Remove the existing https://search-beta.imin.co/v2/search/sessions endpoint

The following facets are included in this update:

- `activity-facet`
- `category-facet` (note that this will change in the near future so is best ignored for now)
- `accessibilitySupport-facet`
- `genderRestriction-facet`
- `dayOfWeek-facet`

Example of new schema:

```
{
  "@context": "https://www.openactive.io/ns/oa.jsonld",
  "type": "Collection",
  "id": "https://example.com/api/sessions?latitude=0.1232334&longitude=0.23423423",
  "totalItems": 3,
  "ext:facet": {
    "activity-facet": {
      "type": "Collection",
      "id": "https://example.com/api/sessions?latitude=0.1232334&longitude=0.23423423#!/activites"
      "totalItems": 1,
      "items": [{
        "type": "Concept",
        "id": "http://openactive.io/activity-list/#d5f...",
        "identifier": "d5f...",
        "prefLabel": "Swimming",
        "count": 3
      }]
    },
    "genderRestriction-facet": {
      // ...etc
    }
  },
  // ...etc
}
```

**Comment by lukehesluke** [comment]
@nickevansuk should this be `imin:facets` for now?
