### ISSUE TITLE
Update sort parameters

### ISSUE THREAD

**Issue by nickevansuk** [imin-ltd/prototype#11]
- `sort=subEvent.startDate,asc` - Sort by latest startDate
- `sort=location.geo,nearest` - Sort by nearest in radial search
- `sort=offers.imin:publicAdultPrice,asc`- Sort by price, lowest first
- `sort=offers.imin:publicAdultPrice,desc` - Sort by price, highest first

According to https://github.com/openactive/opportunity-api/issues/4

**Comment by nishaldesai** [comment]
update:
Currently functional:
- subEvent.startDate,asc: Sorted from earliest to latest after datetime specified (defaults to NOW)

Not yet implemented
- location.geo,nearest: Sorted from nearest to farthest to location specified in query
- offers.imin:publicAdultPrice,asc: Sorted from lowest to highest price
- offers.imin:publicAdultPrice,desc: Sorted from highest to lowest price
