### ISSUE TITLE
BroadcastEvent and VirtualEvent

### ISSUE THREAD

**Issue by nickevansuk** [imin-ltd/prototype#5]
Following these recommendations: https://github.com/openactive/modelling-opportunity-data/issues/71

BroadcastEvent (for events that are broadcast only to specific locations):
```
{
   "type": "BroadcastEvent" 
}
```
or

VirtualEvent (online events that are live-streamed):
```
{
   "type": "imin:VirtualEvent"
}
```

check on an object:
  - `item.type == "BroadcastEvent" || item.type == "imin:VirtualEvent"`

filter:
  - `&type[in]=BroadcastEvent,imin:VirtualEvent`

**Comment by lukehesluke** [comment]
@nickevansuk so:

- a BroadcastEvent should look like a normal event except it has multiple values for location?
- a VirtualEvent should look like a normal event except that it has no location?

**Comment by nickevansuk** [comment]
TBH I'd only implement VirtualEvent for now, as BroadcastEvent isn't something they've asked for and Google's schema.org profile doesn't support multiple locations (location is not an array).

Yes VirtualEvent is normal without location

**Comment by lukehesluke** [comment]
@nickevansuk since VirtualEvents have no location, here's a suggested filtering strategy:

- A consumer can exclude `location.geo[radial]=` iff they have `type=imin:VirtualEvent`
- When including `location.geo[radial]=`, VirtualEvents will not be returned

**Comment by nickevansuk** [comment]
Sounds great!
